<?php

namespace OHMedia\WysiwygBundle\Util;

class HtmlTags
{
    // Lists curated from https://developer.mozilla.org/en-US/docs/Web/HTML/Element

    public const SAFE = [
        'a',
        'abbr',
        'address',
        'article',
        'aside',
        'audio',
        'b',
        'bdi',
        'bdo',
        'blockquote',
        'br',
        'button',
        'caption',
        'cite',
        'code',
        'col',
        'colgroup',
        'data',
        'del',
        'details',
        'dd',
        'dfn',
        'div',
        'dl',
        'dt',
        'em',
        'figcaption',
        'figure',
        'i',
        'img',
        'ins',
        'hr',
        'h1',
        'h2',
        'h3',
        'h4',
        'h5',
        'h6',
        'kbd',
        'li',
        'mark',
        'math',
        'menu',
        'nav',
        'ol',
        'p',
        'pre',
        'picture',
        'q',
        'rp',
        'rt',
        'ruby',
        's',
        'samp',
        'section',
        'source',
        'small',
        'span',
        'strong',
        'sub',
        'summary',
        'sup',
        'table',
        'tbody',
        'td',
        'tfoot',
        'th',
        'thead',
        'tr',
        'track',
        'time',
        'u',
        'ul',
        'var',
        'video',
        'wbr',
    ];

    public const UNSAFE = [
        'area',
        'base',
        'body',
        'canvas',
        'datalist',
        'dialog',
        'embed',
        'fieldset',
        'form',
        'footer',
        'head',
        'header',
        'html',
        'iframe',
        'input',
        'label',
        'legend',
        'link',
        'main',
        'map',
        'meta',
        'meter',
        'noscript',
        'object',
        'optgroup',
        'option',
        'output',
        'param',
        'portal',
        'progress',
        'select',
        'script',
        'slot',
        'style',
        'svg',
        'template',
        'textarea',
        'title',
    ];

    public static function htmlTagsToTinymceElements(string ...$tags): string
    {
        return implode(',', array_map(function ($tag) {
            return ('p' === $tag ? '#' : '').$tag.'[*]';
        }, $tags));
    }
}
