services:
    OHMedia\WysiwygBundle\Form\Type\WysiwygType:
        arguments: ["%oh_media_wysiwyg.wysiwyg.sitekey%", "%oh_media_wysiwyg.wysiwyg.theme%", "%oh_media_wysiwyg.wysiwyg.size%"]
        tags:
            - { name: form.type }

    oh_media_wysiwyg.form.type.wysiwyg:
        alias: OHMedia\WysiwygBundle\Form\Type\WysiwygType

    OHMedia\WysiwygBundle\Validator\WysiwygValidator:
        arguments: ["@request_stack", "%oh_media_wysiwyg.wysiwyg.secretkey%"]
        tags:
            - { name: validator.constraint_validator }

    oh_media_wysiwyg.validator.wysiwyg:
        alias: OHMedia\WysiwygBundle\Validator\WysiwygValidator
