services:
    OHMedia\WysiwygBundle\Service\Wysiwyg:
        arguments: ["@twig", "%oh_media_wysiwyg.allowed_tags%"]

    oh_media_wysiwyg.wysiwyg:
        alias: OHMedia\WysiwygBundle\Service\Wysiwyg

    OHMedia\WysiwygBundle\Form\Type\WysiwygType:
        arguments: ["@oh_media_wysiwyg.wysiwyg"]
        tags:
            - { name: form.type }

    oh_media_wysiwyg.form.type.wysiwyg:
        alias: OHMedia\WysiwygBundle\Form\Type\WysiwygType

    oh_media_wysiwyg.twig_extension:
        class: OHMedia\WysiwygBundle\Twig\Extension\WysiwygExtension
        arguments: ["@oh_media_wysiwyg.wysiwyg"]
        tags:
            - { name: twig.extension }
