services:
    OHMedia\WysiwygBundle\Service\Wysiwyg:
        arguments: ["@twig.loader"]

    oh_media_wysiwyg.wysiwyg:
        alias: OHMedia\WysiwygBundle\Service\Wysiwyg

    OHMedia\WysiwygBundle\Form\Type\WysiwygType:
        arguments: ["%oh_media_wysiwyg.allowed_tags%"]
        tags:
            - { name: form.type }

    oh_media_wysiwyg.form.type.wysiwyg:
        alias: OHMedia\WysiwygBundle\Form\Type\WysiwygType
